server:
  port: 2002
spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: ccp_tx_group
    nacos:
      discovery:
        server-addr: 47.103.7.32:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.103.7.32:3306/seata_account?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    druid:
      validation-query: select 1
      test-on-return: false
      test-while-idle: true
      test-on-borrow: false
feign:
  hystrix:
    enabled: false
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      ccp:
        springcloud: debug