server:
  port: 8001
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.103.7.32:3306/cloud_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    druid:
      validation-query: SELECT 1
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样值介于 0 到1 之间，1则表示全部采集
      probability: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ccp.springcloud.entities

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进eurekaServer，默认为true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001   #修改主机名
    prefer-ip-address: true    #访问路径显示IP
    # Eureka客户端向服务端发送的心跳间隔，单位为秒，默认30
#    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳等待的时间上限，单位为秒，默认90，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2