server:
  port: 9527

spring:
  devtools:
    restart:
      enabled: true
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               # 开启从注册中心动态创建路由的功能，利用微服务名进行路由

      routes:
        - id: payment_routh             #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/get/**      # 断言，路径相匹配的进行路由

        - id: payment_routh2             #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/lb/**      # 断言，路径相匹配的进行路由
#            - Cookie=name,ccp
#            - Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Query=red,gree.*
eureka:
  instance:
    hostname: cloud-gateway-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true